# Generated by Django 5.2.7 on 2025-10-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Kullanıcının dahil olduğu gruplar.', related_name='customuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('support', 'Support'), ('customer', 'Customer')], default='customer', help_text='Kullanıcının sistemdeki rolünü belirtir.', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Kullanıcının sahip olduğu özel izinler.', related_name='customuser_permissions_set', to='auth.permission'),
        ),
    ]
