# Generated by Django 5.2.7 on 2025-10-24 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Yardım Masası', max_length=200)),
                ('site_description', models.TextField(default='Müşteri destek ve talep yönetim sistemi')),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=50)),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('token_expiry_days', models.PositiveIntegerField(default=30)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('require_password_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
