# Generated by Django 5.2.7 on 2025-10-28 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsettings'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customauthtoken',
            options={'ordering': ['-created'], 'verbose_name': 'Auth Token', 'verbose_name_plural': 'Auth Tokens'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Sistem Ayarları', 'verbose_name_plural': 'Sistem Ayarları'},
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Token oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='expires_at',
            field=models.DateTimeField(help_text="Token'ın geçerlilik süresi"),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Token'ın aktif olup olmadığı"),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='key',
            field=models.CharField(help_text='Token için benzersiz anahtar', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text="Token'ın son kullanıldığı tarih", null=True),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='password_hash',
            field=models.CharField(help_text="Hash'lenmiş şifre", max_length=255),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='user',
            field=models.OneToOneField(help_text="Token'ın sahibi olan kullanıcı", on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='username',
            field=models.CharField(help_text='Kullanıcı adı (performans için)', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Bu kullanıcının ait olduğu gruplar. Bir kullanıcı grupları aracılığıyla belirli izinleri alır.', related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Bu kullanıcının sahip olduğu özel izinler.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='admin_email',
            field=models.EmailField(default='admin@example.com', help_text='Sistem yöneticisi e-posta adresi', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Maksimum giriş denemesi sayısı'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='require_password_change',
            field=models.BooleanField(default=False, help_text='İlk girişte şifre değişimi zorunlu mu?'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Oturum zaman aşımı (dakika)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='site_description',
            field=models.TextField(default='Müşteri destek ve talep yönetim sistemi', help_text='Site açıklaması'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='site_name',
            field=models.CharField(default='Yardım Masası', help_text='Sitenin adı', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP sunucu adresi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP şifresi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP port numarası'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='TLS kullanılıp kullanılmayacağı'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='SMTP kullanıcı adı', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='timezone',
            field=models.CharField(default='Europe/Istanbul', help_text='Sistem zaman dilimi', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='token_expiry_days',
            field=models.PositiveIntegerField(default=30, help_text='Token geçerlilik süresi (gün)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Son güncelleyen kullanıcı', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='customauthtoken',
            table='accounts_customauthtoken',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table='accounts_systemsettings',
        ),
    ]
