# Generated by Django 5.2.7 on 2025-11-03 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customauthtoken_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customauthtoken',
            name='username',
        ),
        migrations.AddField(
            model_name='customauthtoken',
            name='device_name',
            field=models.CharField(default='Unknown device', help_text='Token hangi cihaz için oluşturuldu', max_length=100),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Token aktif mi?'),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Son kullanım tarihi', null=True),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='password_hash',
            field=models.CharField(blank=True, help_text="Hash'lenmiş şifre", max_length=255),
        ),
        migrations.AlterField(
            model_name='customauthtoken',
            name='user',
            field=models.ForeignKey(help_text="Token'ın sahibi olan kullanıcı", on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Bu kullanıcının ait olduğu gruplar.', related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Maks giriş denemesi'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Oturum zaman aşımı'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP port'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='TLS kullanımı'),
        ),
    ]
