# Generated by Django 5.2.7 on 2025-11-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customauthtoken_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_2fa',
            field=models.BooleanField(default=False, help_text='İki faktörlü kimlik doğrulama aktif mi?'),
        ),
    ]
