# Generated by Django 5.2.7 on 2025-11-04 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_systemsettings_enable_2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('CRITICAL', 'Kritik')], default='INFO', max_length=10, verbose_name='Seviye')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('action', models.CharField(max_length=100, verbose_name='İşlem')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Ek Veri')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
                'db_table': 'accounts_systemlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
