# Generated by Django 5.2.7 on 2025-10-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]