# Generated by Django 5.2.7 on 2025-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('open', 'Açık'), ('pending', 'Beklemede'), ('closed', 'Kapatıldı'), ('wrong_department', 'Yanlış Bölüm')], default='new', max_length=20),
        ),
    ]
