# Generated by Django 5.2.7 on 2025-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('open', 'Açık'), ('pending', 'Beklemede'), ('closed', 'Kapatıldı'), ('wrong_section', 'Yanlış Bölüm / Kapatıldı')], default='new', max_length=20),
        ),
    ]
