# Generated by Django 5.2.7 on 2025-10-17 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ticket',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='sla',
            options={'verbose_name': 'Servis Düzeyi Anlaşması (SLA)', 'verbose_name_plural': 'Servis Düzeyi Anlaşmaları'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='SLA Adı'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='resolve_time',
            field=models.IntegerField(help_text='Çözüm süresi (saat)', verbose_name='Çözüm Süresi (saat)'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='response_time',
            field=models.IntegerField(help_text='Yanıt süresi (saat)', verbose_name='Yanıt Süresi (saat)'),
        ),
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Talep Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('open', 'Açık'), ('pending', 'Beklemede'), ('closed', 'Kapatıldı'), ('wrong_section', 'Yanlış Bölüm / Kapatıldı')], default='new', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('talep_numarasi', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Talep Numarası')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_talepler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kullanıcı')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.category', verbose_name='Kategori')),
                ('sla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.sla', verbose_name='SLA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Talep',
                'verbose_name_plural': 'Talepler',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='talep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='tickets.talep', verbose_name='Talep'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
