# Generated by Django 5.2.7 on 2025-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_comment_ticket_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talep',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('seen', 'Görüldü'), ('open', 'Açık'), ('pending', 'Beklemeye Alındı'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı'), ('wrong_section', 'Yanlış Bölüm')], default='new', max_length=20, verbose_name='Durum'),
        ),
    ]
