# Generated by Django 5.2.7 on 2025-10-28 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_talep_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='sla',
            options={'ordering': ['response_time'], 'verbose_name': 'Servis Düzeyi Anlaşması (SLA)', 'verbose_name_plural': 'Servis Düzeyi Anlaşmaları'},
        ),
        migrations.AlterModelOptions(
            name='talep',
            options={'ordering': ['-created_at'], 'verbose_name': 'Talep', 'verbose_name_plural': 'Talepler'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Talep kategorisinin adı (Donanım, Yazılım vb.)', max_length=100, unique=True, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(help_text='Yorum veya mesaj içeriği', verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='talep',
            field=models.ForeignKey(blank=True, help_text='Yorumun ait olduğu ticket', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='tickets.talep', verbose_name='Talep'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Yorumu yazan kullanıcı', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='name',
            field=models.CharField(help_text='SLA seviyesinin adı (Kritik, Normal, Düşük vb.)', max_length=100, unique=True, verbose_name='SLA Adı'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='resolve_time',
            field=models.IntegerField(help_text='Sorunu çözmek için verilen maksimum süre (saat cinsinden)', verbose_name='Çözüm Süresi (saat)'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='response_time',
            field=models.IntegerField(help_text='İlk yanıt verilmesi gereken süre (saat cinsinden)', verbose_name='Yanıt Süresi (saat)'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="Ticket'ı çözecek olan kullanıcı", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_talepler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Ticket kategorisi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='description',
            field=models.TextField(help_text='Sorunun detaylı açıklaması', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', help_text="Ticket'ın önem seviyesi", max_length=20, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='sla',
            field=models.ForeignKey(blank=True, help_text='Uygulanan servis düzeyi anlaşması', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.sla', verbose_name='SLA'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('seen', 'Görüldü'), ('open', 'Açık'), ('pending', 'Beklemeye Alındı'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı'), ('wrong_section', 'Yanlış Bölüm')], default='new', help_text="Ticket'ın mevcut durumu", max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='talep_numarasi',
            field=models.PositiveIntegerField(blank=True, help_text='Sistem tarafından otomatik atanan benzersiz numara', null=True, unique=True, verbose_name='Talep Numarası'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='title',
            field=models.CharField(help_text='Kısa ve açıklayıcı ticket başlığı', max_length=200, verbose_name='Talep Başlığı'),
        ),
        migrations.AlterField(
            model_name='talep',
            name='user',
            field=models.ForeignKey(help_text="Ticket'ı oluşturan kullanıcı", on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı'),
        ),
    ]
