# Generated by Django 5.2.7 on 2025-11-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Kategori hakkında detaylı açıklama', null=True, verbose_name='Açıklama'),
        ),
    ]
