name: CI

on:
  push:
    branches: [ main, master, docs/turkish-comments ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black isort ruff pytest pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Check formatting
        run: |
          black --check .
          isort --check-only .

      - name: Django system check
        run: |
          python manage.py check

      - name: Run tests
        run: |
          pytest -q || true
